site_name: Documentação forUnB
repo_url: https://github.com/unb-mds/2024-1-forUnB
extra_css:
- stylesheets/extra.css

theme: 
  name: material
  favicon: assets/for_unb.png
  logo: assets/for_unb.png
  palette:
    primary: custom

nav:

  - Home: index.md
  - Visão do produto: visao_do_produto/visao_produto.md
  - Arquitetura:  arquitetura/arquitetura.md
  - Protótipos: prototipo/prototipo.md

  - Sprints:
      - Sprint 0: sprints/sprint0.md
      - Sprint 1: sprints/sprint1.md
      - Sprint 2: sprints/sprint2.md
      - Sprint 3: sprints/sprint3.md
      - Sprint 4: sprints/sprint4.md
      - Sprint 5: sprints/sprint5.md
      - Sprint 6: sprints/sprint6.md
      - Sprint 7: sprints/sprint7.md
      - Sprint 8: sprints/sprint8.md
      - Sprint 9: sprints/sprint9.md
      - Sprint 10: sprints/sprint10.md
      - Sprint 11: sprints/sprint11.md

  - Estudos:
      - Lean Inception: lean_inception/lean_inception.md
      - Métodos Ágeis: estudos/metodos-ageis.md
      - MkDocs: estudos/documentacao.md
      - GitFlow: estudos/gitflow.md
      - Bibliografia: estudos/bibliografia.md

  - Scraping: scraping/scraping.md
      