# Generated by Django 4.2.13 on 2024-08-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_answer_is_anonymous_question_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='description',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='answer',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Modo anônimo'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=100, verbose_name=''),
        ),
    ]
