# Generated by Django 5.0.4 on 2024-08-08 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_answer_description_alter_answer_is_anonymous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='upvotes',
            field=models.IntegerField(default=0, verbose_name='Upvotes'),
        ),
    ]
