# Generated by Django 4.2.13 on 2024-07-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_forum_description'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_answers',
            field=models.ManyToManyField(related_name='created_by', to='main.answer'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='created_questions',
            field=models.ManyToManyField(related_name='created_by', to='main.question'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='followed_forums',
            field=models.ManyToManyField(blank=True, related_name='followers', to='main.forum'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='liked_questions',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='main.question'),
        ),
    ]
