# Generated by Django 5.0.4 on 2024-08-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_answer_upvotes_remove_question_upvotes'),
        ('users', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_answers',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='main.answer'),
        ),
    ]
