# Generated by Django 5.0.4 on 2024-08-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_answer_upvotes_answer_upvoters_and_more'),
        ('users', '0005_alter_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='liked_answers',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='main.answer'),
        ),
    ]
